name: Hello, Python

on: push

jobs:
    run_python:
        name: Run Ubuntu's Python
        runs-on: ubuntu-latest
        steps:
            - run: python --version

    run_specific_python:
        name: Run Python 3.13
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v5
              with: 
                python-version: '3.13'
            - run: python --version