name: Run bash script tests

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Make bash test script executable
              run: chmod +x ./run_tests.sh

            - name: Run bash test script
              run: ./run_tests.sh

