name: Test

on: 
    push:
        branches:
            - main


jobs:
    test:
        name: Run Tests with Python 3.13
        runs-on: ubuntu_latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - run: python --version
            - run: python -m pip install -r requirements_dev.txt
            - run: pytest